version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: freqtrade_web_1
      APP_PORT: 8080

  web:
    image: freqtradeorg/freqtrade:stable_freqaitorch
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - ${APP_DATA_DIR}/user_data:/freqtrade/user_data
    ports:
      - "8080:8080"  # For FreqUI
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
      --config /freqtrade/user_data/config.json
      --strategy NOTankAi_15
      --freqaimodel LightGBMRegressor
